### ISSUE TITLE
Play in queue in one MPV

### ISSUE THREAD

**Issue by lbpth** [tuilakhanh/mpv-config#1]
Hiện tại để tạo playlist tự do, có 1 cách khá hay với bản mpv-config hiện tại của tuilakhanh - là sử dụng Copy rồi Ctrl V vào cửa sổ MPV đang chạy. 
Nhờ bác tuilakhanh nghiên cứu thêm phương án kéo thả cho nhanh, tức cầm link, kéo thẳng vào MPV là chạy thay vì Copy rồi Ctrl V

**Comment by tuilakhanh** [comment]
Thím thêm `drag-and-drop=append` vào trong mpv.conf là được nhé.
