### ISSUE TITLE
How to install mpv-git on Linux?

### ISSUE THREAD

**Issue by ghost** [tuilakhanh/mpv-config#3]
I found this project on Reddit. It is said that it requires mpv-git. I'm running Debian Linux and I don't know how to get mpv-git. mpv (0.35.1-4) is the latest version we have on Debian Bookworm.

https://packages.debian.org/bookworm/mpv

**Comment by tuilakhanh** [comment]
You can use [office helper scripts](https://github.com/mpv-player/mpv-build) to build latest version. Follow their instruction, also remember to choose master version.
